LOGIN_PAGE = "https://pc.xuexi.cn/points/login.html"
POINTS_PAGE="https://pc.xuexi.cn/points/my-points.html"
INVALID_ADDR_HEAD="https://www.xuexi.cn/lgpage/detail/index.html?id="
DAILY_EXAM_PAGE="https://pc.xuexi.cn/points/exam-practice.html"
WEEKLY_EXAM_PAGE="https://pc.xuexi.cn/points/exam-weekly-list.html"
SPECIAL_EXAM_PAGE="https://pc.xuexi.cn/points/exam-paper-list.html"
NOT_FOUND_PAGE="https://xuexi.cn/notFound.html"
