name: Build Packages
on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    name: Build .whl package and .pkg.tar.* package
    runs-on: ubuntu-latest
    steps:
      - name: Print info
        run: echo github.ref is ${{ github.ref }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with: 
          python-version: '3.10'
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v7
      - name: Build Poetry Package
        run: poetry build
      - name: Build Arch Package
        id: arch-package
        uses: ouuan/pkgbuild-action@v1.0.0
        with: 
          path: resources/makepkg
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith( github.ref, 'refs/tags/v')
        with:
          files: |
            dist/*
            ${{ steps.arch-package.outputs.pkgfile }}
          generate_release_notes: true
