name: Build Packages and Push to TechXuexi
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with: 
          python-version: '3.10'
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v7
      - name: Build Poetry Package
        run: poetry build
      - name: Build Arch Package
        uses: ouuan/pkgbuild-action@v1.0.0
        with: 
          path: resources/makepkg
      - name: Get Short SHA
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
            resources/makepkg/*.pkg.tar.*
          generate_release_notes: true
          tag_name: 2-${{ steps.short-sha.outputs.sha }}

          
      
